"""Added description to Event, price to Ticket

Revision ID: 003563487fd3
Revises: 27ceacc0b495
Create Date: 2025-05-27 18:22:20.048020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003563487fd3'
down_revision: Union[str, None] = '27ceacc0b495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('events', sa.Column('description', sa.String(), nullable=True))
    # op.add_column('tickets', sa.Column('price', sa.Integer(), nullable=False))
    # op.alter_column('tickets', 'status',
            #    existing_type=sa.VARCHAR(),
            #    nullable=False)
    # ### end Alembic commands ###


    def downgrade() -> None:
        op.drop_column('tickets', 'price')
        op.drop_column('events', 'description')

    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('tickets', 'status',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    
    # ### end Alembic commands ###
